ga4_modeling:
  outputs:
    dev:
      dataset: ga4_modeling
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ var('gcp_project') }}"
      threads: 4
      type: bigquery
  target: dev