

-- Generated by AutomateDV (formerly known as dbtvault)

    WITH source_data AS (
    SELECT DISTINCT s.CUSTOMER_PK, s.CUSTOMER_PHONE, s.CUSTOMER_NAME, s.CUSTOMER_HASHDIFF, s.EFFECTIVE_FROM, s.RECORD_SOURCE
    FROM `sweepsump`.`tpch_sf10_test`.`v_stg_orders` AS s
    WHERE s.CUSTOMER_PK IS NOT NULL
        AND s.CUSTOMER_PHONE IS NOT NULL
),



records_to_insert AS (

    SELECT source_data.CUSTOMER_PK, source_data.CUSTOMER_PHONE, source_data.CUSTOMER_NAME, source_data.CUSTOMER_HASHDIFF, source_data.EFFECTIVE_FROM, source_data.RECORD_SOURCE
    FROM source_data


)

SELECT * FROM records_to_insert