datavault_test:
  outputs:
    dev:
      dataset: dbt_datamodeling
      method: oauth
      project: sweepsump
      threads: 4
      type: bigquery
  target: dev
dbt_dimensional_modeling:
  outputs:
    dev:
      dataset: dbt_dimensional_modeling
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: sweepsump
      threads: 4
      type: bigquery
  target: dev
  