# =============================================================================
# dbt Profiles 設定（CI/CD用）
# =============================================================================
# GitHub Actions等のCI環境で使用するプロファイル設定
# DBT_PROFILES_DIR をこのディレクトリに設定して使用
#
# 環境変数:
#   - DBT_BQ_PROJECT: GCPプロジェクトID（必須）
#   - DBT_BQ_DATASET: 書き込み先データセット名（dev/ci用）
#   - DBT_BQ_LOCATION: BigQueryロケーション（デフォルト: US）
#
# =============================================================================

dbt_ci_test:
  target: dev
  outputs:
    # -------------------------------------------------------------------------
    # dev: ローカル開発環境
    # -------------------------------------------------------------------------
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT', 'sweepsump') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET', 'dbt_ci_test') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive

    # -------------------------------------------------------------------------
    # ci: GitHub Actions CI環境
    # -------------------------------------------------------------------------
    ci:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET', 'dbt_ci') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive

    # -------------------------------------------------------------------------
    # prod: 本番環境
    # -------------------------------------------------------------------------
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: dbt_ci_test_prod
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: batch
