version: "3"

services: 
  db:
    image: postgres:13.4
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: sample
      
  digdag:
    build:
        context: .
        dockerfile: Dockerfile
    volumes: 
      - ./project:/work
    ports:
      - 65432:65432
    # command: /bin/sh -c "while sleep 1000; do :; done"
  